services:
  
  #Banco de dados
  postgre:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: vendas123
      POSTGRES_USER: uservendas
      POSTGRES_DB: vendas
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - vendas
volumes:
  postgre_docker_vol:
    name: postgre_vol

networks:
  vendas:
    name: vendas
    driver: bridge
